name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - 'release/v*'
  pull_request:
    branches:
      - master
      - 'release/v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tags
        id: meta
        run: |
          echo "REPO=ghcr.io/${{ github.repository }}" >> $GITHUB_OUTPUT

          if [[ "${GITHUB_REF_NAME}" == "master" ]]; then
            echo "TAGS=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == release/v* ]]; then
            VERSION="${GITHUB_REF_NAME#release/}"  # removes 'release/' prefix
            echo "TAGS=stg-v$VERSION stg" >> $GITHUB_OUTPUT
          else
            echo "TAGS=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.REPO }}:${{ steps.meta.outputs.TAGS }}
